package-lock.json
package.json

Add missing @typescript-eslint/parser dependency

---

package-lock.json
package.json
src/index.ts

Add all and recommended configs

---

README.md

Updated readme with configs

---

package-lock.json
package.json

Update for eslint 8.x

---

.gitignore
.travis.yml
LICENSE.txt
README.md
package-lock.json
package.json
src/file-path-comment.spec.ts
src/file-path-comment.ts
src/index.ts
src/no-card-numbers.spec.ts
src/no-card-numbers.ts

Update dependencies to node 16 and typescript 4.7

---

.eslintrc
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.travis.yml
README.md
SECURITY.md
package-lock.json
package.json
src/index.ts
src/no-card-numbers.ts
src/no-uuid.spec.ts
src/no-uuid.ts
tsconfig.json

Add no-uuid rule

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/publish-beta.yml
LICENSE.txt
README.md
package-lock.json
package.json
src/no-card-numbers.spec.ts
src/no-card-numbers.ts
src/no-uuid.ts

ignore card numbers with invalid prefix

---

package-lock.json
package.json
src/index.ts
src/regular-expression-comment.spec.ts
src/regular-expression-comment.ts

Added new eslint-rule regular-expression-comment

---

package-lock.json
package.json
src/index.ts
src/require-strict-assert.spec.ts
src/require-strict-assert.ts

Added new rule require-strict-assert

---

.github/workflows/check-pr-reviews.yml
.github/workflows/check-published-scheduled.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/publish-beta.yml
.github/workflows/publish.yml
.gitignore
LICENSE.txt
README.md
package-lock.json
package.json
src/index.ts
src/object-literal-response.spec.ts
src/object-literal-response.ts

add new rule to enforce object literal to be used in setResponse

---

package-lock.json
package.json
src/regular-expression-comment.spec.ts
src/regular-expression-comment.ts

Fixed to allow simple text-only regexs to not have a comment

---

README.md
docs/rules/no-promise-instance-method.md
package-lock.json
package.json
src/index.ts
src/no-promise-instance-method.spec.ts
src/no-promise-instance-method.ts
src/tester.test.ts

implement no-promise-instance-method rule

---

.eslintrc
docs/rules/require-resolve-full-response.md
package-lock.json
package.json
src/index.ts
src/library/format.ts
src/library/tree.ts
src/library/ts-tree.ts
src/library/variable.ts
src/require-resolve-full-response.spec.ts
src/require-resolve-full-response.ts
src/ts-tester.test.ts

add new rule require-resolve-full-response

---

package-lock.json
package.json
src/agent/no-serve-runtime.spec.ts
src/agent/no-serve-runtime.ts
src/index.ts

add new rule to disallow the usage of @checkdigit/serve-runtime

---

package-lock.json
package.json
src/require-fixed-services-import.spec.ts
src/require-fixed-services-import.ts

update require-fixed-services-import rule to allow index and index.ts imports

---

package-lock.json
package.json
src/no-duplicated-imports.spec.ts
src/no-duplicated-imports.ts

Fix no-duplicated-imports rule to exclude non-mergable namespace imports 

---

package-lock.json
package.json
src/require-fixed-services-import.spec.ts
src/require-fixed-services-import.ts

update service typing import rules to enforce fixed paths and service typing namespaces

---

README.md
docs/rules/require-ts-extension-imports.md
package-lock.json
package.json
src/index.ts
src/require-ts-extension-imports.spec.ts
src/require-ts-extension-imports.ts

Closes #99 
Tested with the internal services

Require ts file extension imports

---

package-lock.json
package.json
src/no-side-effects.spec.ts
src/no-side-effects.ts

Fixed the no-side-effects anything inside function definition is not a side-effect

---

package-lock.json
package.json
src/require-fixed-services-import.spec.ts
src/require-fixed-services-import.ts

only match services folder directly beneath src folder

---

.github/workflows/ci.yml
package-lock.json
package.json
src/require-ts-extension-imports-exports.spec.ts
src/require-ts-extension-imports-exports.ts

Closes #131 
tested it on internal services

Resolved missing .ts file references in namespace exports
